version: "3.8"

services:
  app:
    build: .
    image: transcendence:latest
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - transcendence_volume:/app/runtime
      - db_volume:/app/db
      - avatars_volume:/app/client/avatars
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - WORK_DIR=${WORK_DIR}
      - USER=${USER}
      - SESSION_MANAGER=${SESSION_MANAGER}

volumes:
  transcendence_volume:
    name: transcendence_volume
    driver: local
    driver_opts:
      type: none
      device: /sgoinfre/${USER}/transcendence
      o: bind
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ./src/db
      o: bind
  avatars_volume:
    name: avatars_volume
    driver: local
    driver_opts:
      type: none
      device: ./client/avatars
      o: bind

