version: "3.8"

services:
  app:
    build: .
    image: transcendence:latest
    ports:
      - "3000:3000"
    restart: always

    environment:
      .env
      - NODE_ENV=production


