

services:
  app:
    image: ${IMAGE_NAME}
    build: .
    ports:
      - "${SCHOOL_PORT}:${SCHOOL_PORT}"
    restart: always

    env_file:
      - .env

    environment:
      - NODE_ENV=production
    volumes:
      # DB and avatars go into shared runtime path
      - /goinfre/${USER}/${IMAGE_NAME}/db:/app/db
      - /goinfre/${USER}/${IMAGE_NAME}/avatars:/app/client/avatars

