services:
  dev:
    build:
      context: .
      target: builder-front
    image: transcendence-dev
    command:
      - sh
      - -c
      - |
        # watch CSS in background
        npx postcss client/src/css/input.css \
          --output client/dist/output.css \
          --watch &

        # then watch & bundle JS forever
        npx esbuild client/src/app.ts \
          --bundle \
          --outfile=client/dist/app.js \
          --platform=browser \
          --format=esm \
          --sourcemap \
          --watch=forever
    volumes:
      - ./client/src:/app/client/src
      - ./shared:/app/client/src/shared
      - ./tailwind.config.js:/app/tailwind.config.js
      -  dist_volume:/app/client/dist
      - ./postcss.config.js:/app/postcss.config.js
    stdin_open: true
    tty: true

  app:
    build: .
    image: transcendence:latest
    depends_on:
      vault-init:
        condition: service_completed_successfully
      dev:
        condition: service_started
    
    volumes:
      - ./client/src:/app/client/src
      - dist_volume:/app/client/dist
      - ./src:/app/src
      - transcendence_volume:/app/runtime
      - db_volume:/app/db
      - avatars_volume:/app/client/avatars
      - shared_volume:/app/client/shared
      - asset_volume:/app/client/assets
      - vault_secrets:/app/vault
    restart: always
    env_file:
      - .env
    environment:
      - VAULT_ADDR=http://vault:8200
      - NODE_ENV=production
      - PORT=${PORT}
      - WORK_DIR=${WORK_DIR}
      - USER=${USER}
      - SESSION_MANAGER=${SESSION_MANAGER}
    networks:
      - transcendence_net


  vault:
     image: hashicorp/vault:1.19
     container_name: vault
     ports:
      # - "8200:8200"
      - "127.0.0.1:8200:8200"
     environment:
      VAULT_ADDR: 'http://127.0.0.1:8200'
     volumes:
      - vault_data:/vault/file
      - ./vault/config:/vault/config
     cap_add:
      - IPC_LOCK
     command: server
     networks:
      - transcendence_net

  vault-init:
    image: hashicorp/vault:1.19
    container_name: vault-init
    depends_on:
      - vault
    volumes:
      - ./vault/scripts:/vault/scripts
      - vault_secrets:/vault/data
    working_dir: /vault/scripts
    entrypoint: /bin/sh
    # command: -c "apk add --no-cache bash netcat-openbsd jq && ./init.sh && ./init-value.sh"
    command: -c "apk add --no-cache bash netcat-openbsd jq dos2unix \
      && dos2unix init.sh init-value.sh \
      && chmod +x init.sh init-value.sh \
      && bash ./init.sh && bash ./init-value.sh" # commente tout ca et remet l'ancien 
    networks:
      - transcendence_net
    environment:
      - VAULT_ADDR=http://vault:8200

  waf:
    build:
      context: ./src/WAF
      args:
        - APP_TARGET_PORT_BUILD_ARG=${PORT}
    ports:
      - "1400:1400"
      - "1800:1800"
    depends_on:
      - app
    volumes:
      - ./src/WAF/logs:/var/log/nginx
    networks:
      - transcendence_net

volumes:
  vault_secrets: {}
  dist_volume: {}
  transcendence_volume:
    name: transcendence_volume
    driver: local
    driver_opts:
      type: none
      device: /goinfre/${USER}/transcendence
      o: bind
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ./src/db
      o: bind
  avatars_volume:
    name: avatars_volume
    driver: local
    driver_opts:
      type: none
      device: ./client/avatars
      o: bind
  asset_volume:
    name: asset_volume
    driver: local
    driver_opts:
     type: none
     device: ./client/assets
     o: bind
  shared_volume:
   name: shared_volume
   driver: local
   driver_opts:
    type: none
    device: ./shared
    o: bind
  vault_data:

networks:
  transcendence_net:
    driver: bridge

