version: "3.8"

services:
  app:
    build: .
    image: transcendence:latest
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - transcendence_volume:/app/db
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - WORK_DIR=${WORK_DIR}
      - USER=${USER}
      - SESSION_MANAGER=${SESSION_MANAGER}

volumes:
  transcendence_volume:
    name: transcendence_volume
    driver: local
    driver_opts:
      type: none
      device: /goinfre/${USER}/transcendence
      o: bind

