services:
  app:
    build: .
    image: transcendence:latest
    volumes:
      - ./client/src:/app/client/src
      - ./src:/app/src
      - transcendence_volume:/app/runtime
      - db_volume:/app/db
      - avatars_volume:/app/client/avatars
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - WORK_DIR=${WORK_DIR}
      - USER=${USER}
      - SESSION_MANAGER=${SESSION_MANAGER}
    networks:
      - transcendence_net

  waf:
    build:
      context: ./src/WAF
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
    environment:
      - APP_TARGET_PORT=${PORT}
    networks:
      - transcendence_net

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./src/WAF/vault/data:/vault/file
      - ./src/WAF/vault/config:/vault/config
     # - ./src/WAF/tls:/vault/config/tls
      - ./src/WAF/vault/policies:/vault/policies
    cap_add:
      - IPC_LOCK
    entrypoint: vault
    command: server -config=/vault/config/vault.hcl
    networks:
      - transcendence_net

volumes:
  transcendence_volume:
    name: transcendence_volume
    driver: local
    driver_opts:
      type: none
      device: /goinfre/${USER}/transcendence
      o: bind
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ./src/db
      o: bind
  avatars_volume:
    name: avatars_volume
    driver: local
    driver_opts:
      type: none
      device: ./client/avatars
      o: bind

networks:
  transcendence_net:
    driver: bridge

