services:
  dev:
    build:
      context: .
      target: builder-front
    image: transcendence-dev
    command:
      - sh
      - -c
      - |
        # watch CSS in background
        npx postcss client/src/css/input.css \
          --output client/dist/output.css \
          --watch

        # then watch & bundle JS forever
        npx esbuild client/src/app.ts \
          --bundle \
          --outfile=client/dist/app.js \
          --platform=browser \
          --format=esm \
          --sourcemap \
          --watch=forever
    volumes:
      - ./client/src:/app/client/src
      - ./shared:/app/client/src/shared
      - ./tailwind.config.js:/app/tailwind.config.js
      -  dist_volume:/app/client/dist
      - ./postcss.config.js:/app/postcss.config.js
    stdin_open: true
    tty: true

  app:
    build: .
    image: transcendence:latest
    depends_on:
      - dev
    volumes:
      - ./client/src:/app/client/src
      - dist_volume:/app/client/dist
      - ./src:/app/src
      - transcendence_volume:/app/runtime
      - db_volume:/app/db
      - avatars_volume:/app/client/avatars
      - shared_volume:/app/client/shared
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - WORK_DIR=${WORK_DIR}
      - USER=${USER}
      - SESSION_MANAGER=${SESSION_MANAGER}
    networks:
      - transcendence_net

  waf:
    build:
      context: ./src/WAF
      args:
        - APP_TARGET_PORT_BUILD_ARG=${PORT}
    ports:
      - "1400:1400"
      - "1800:1800"
    depends_on:
      - app
    networks:
      - transcendence_net

volumes:
  dist_volume: {}
  transcendence_volume:
    name: transcendence_volume
    driver: local
    driver_opts:
      type: none
      device: /goinfre/${USER}/transcendence
      o: bind
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      type: none
      device: ./src/db
      o: bind
  avatars_volume:
    name: avatars_volume
    driver: local
    driver_opts:
      type: none
      device: ./client/avatars
      o: bind
  shared_volume:
   name: shared_volume
   driver: local
   driver_opts:
    type: none
    device: ./shared
    o: bind

networks:
  transcendence_net:
    driver: bridge

